"""Generate an ORM-based PostgreSQL DDL reference from app.db.models.

Usage:
    python scripts/gen_schema_sql.py > schema_orm.sql

Compiles CreateTable + CreateIndex for every Table registered in
Base.metadata (sorted by table name) using the SQLAlchemy PostgreSQL
dialect. No database connection is required — everything is compiled
offline from the ORM metadata.

NOTE: the output is a REFERENCE snapshot. The authoritative schema is
always produced by `alembic upgrade head`.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Allow running from anywhere: make the repo root importable (app package).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def main() -> int:
    # Runtime import guard: fail with a clear message instead of a traceback.
    try:
        import sqlalchemy
    except ImportError:
        print(
            "ERROR: sqlalchemy is not installed. Install the project "
            "dependencies first (pip install -r requirements.txt) and "
            "re-run: python scripts/gen_schema_sql.py",
            file=sys.stderr,
        )
        return 1

    from sqlalchemy import Table
    from sqlalchemy.dialects import postgresql
    from sqlalchemy.schema import CreateIndex, CreateTable

    # Importing the models package registers every model module with Base.
    from app.db.models import Base

    dialect = postgresql.dialect()

    print(
        f"-- ORM reference DDL generated by scripts/gen_schema_sql.py "
        f"(SQLAlchemy {sqlalchemy.__version__}, dialect: postgresql)."
    )
    print("-- REFERENCE ONLY - the authoritative schema comes from `alembic upgrade head`.")

    tables = sorted(
        (t for t in Base.metadata.tables.values() if isinstance(t, Table)),
        key=lambda t: t.name,
    )
    for table in tables:
        ddl = str(CreateTable(table).compile(dialect=dialect)).strip()
        print(ddl + ";")
        print()
        for index in sorted(table.indexes, key=lambda i: (i.name or "")):
            index_ddl = str(CreateIndex(index).compile(dialect=dialect)).strip()
            print(index_ddl + ";")
            print()

    print(f"-- {len(tables)} tables compiled from Base.metadata.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
